export const MODEL_CONST = {
	INIT_MODEL: "INIT_MODEL",
	MODEL_CHANGE_START: "MODEL_CHANGE_START",
	MODEL_CHANGE_END: "MODEL_CHANGE_END",
	TASK_CHANGE_END: "TASK_CHANGE_END",
	CLEAR_ERRORS: "CLEAR_ERRORS",
	SET_USER_ROLE_LIST: "SET_USER_ROLE_LIST",
	SET_USER_ROLE_LIST_UPDATE: "SET_USER_ROLE_LIST_UPDATE",
	USER_UPDATE_DATA: "USER_UPDATE_DATA",
	USER_IMAGE_DATA: "USER_IMAGE_DATA",
	TABLE_UPDATE: "TABLE_UPDATE",
	FORM_BUILDER_CLIPBOARD_FIELD: "FORM_BUILDER_CLIPBOARD_FIELD",
};
